### ISSUE TITLE
https ssl not supported

### ISSUE THREAD

**Issue by DanelMalsky** [graniet/chromebackdoor#2]
Form grabber or computer history not show https pages.

**Comment by graniet** [comment]
You need use hosting (Relais) with SSL certificat.

**Comment by DanelMalsky** [comment]
No I mean website with https protocol are not being grabbed. Like https://mail.ru

**Comment by graniet** [comment]
Hi,

![Backdoor lock](http://s32.postimg.org/j1ewu5hc5/Capture_d_e_cran_2016_05_05_a_16_58_49.png)
![Backdoor lock](http://s32.postimg.org/sn3vwpj45/Capture_d_e_cran_2016_05_05_a_17_00_35.png)
![Backdoor lock](http://s32.postimg.org/v6y8lpsw5/Capture_d_e_cran_2016_05_05_a_17_05_46.png)

You need use hosting with SSL, and with python install script use exemple : http**s**://site.com/chromebackdoor_panel/

**Comment by DanelMalsky** [comment]
Not self-signed ?
