### ISSUE TITLE
problem with https

### ISSUE THREAD

**Issue by mattsmithe** [graniet/chromebackdoor#4]
When I run chromebackdoor over http everything is OK and chromebackdoor work correctly But when i change server to https chromebackdoor not work.
I Check SSL Verification and Everything is OK and chromepanel run on it But when run chromebackdoor extension on a chrome device although it run and request my url and response will be correct (Status Code: 200 OK) But in chromepanel nothing add. Means bots panel is empty
But for example when i request
https://mydomain:myport/mychromebackdoorfolder/web/gate.php??add=exampleip&version=Build001
It run and add to bots menu in chromepanel
I dont know whats the problem.
Please help me.
Thanks.

**Comment by graniet** [comment]
Hello !,

The SSL certificate is on relais?
Your relay is on same domain of web folder?
Alphassl is used?

Thanks

**Comment by mattsmithe** [comment]
Hello (Sry)
I set SSL on my apache server and run chromebackdoor on apache.
How can I set SSL certificate on relais ?
I use Letsencrypt for ssl certificate.

**Comment by mattsmithe** [comment]
Hello (Sry)
I set SSL on my apache server and run chromebackdoor on apache.
How can I set SSL certificate on relais ?
I use Letsencrypt for ssl certificate.

**Comment by graniet** [comment]
hello !

i make new video this week end for install new version.

Thanks !
