### ISSUE TITLE
The tutorial video is not update?

### ISSUE THREAD

**Issue by mulysatest** [graniet/chromebackdoor#5]
I am using Kali (Rolling) and test it with Chrome in this OS.

I have followed the installation video, however seems like the script have changed a lot. So, the installation step seems to be odd during this part: https://youtu.be/uc4817555Fc?t=114

However, I managed to setup web, mysql, CRX installation on Chrome properly. 
However once I did surf some websute and refresh the C&C, the web interface didn't show any sign of bot connectivity at all. 

How to debug or fix it?

Note:  "pip install wine32" also produced and error about 

"Downloading/unpacking wine32
  Could not find any downloads that satisfy the requirement wine32
Cleaning up...
No distributions at all found for wine32
Storing debug log for failure in /Users/cmaster/.pip/pip.log"

**Comment by graniet** [comment]
Hello !

I make new video this week end !

Thanks for this report !
